name: Compile

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["1.11", "1.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Environments
        run: |
          echo "SM_VERSION=${{ matrix.version }}" >> $GITHUB_ENV

      - name: Install
        run: |
          bash scripts/install.sh

      - name: Compile
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp -E saxtonhale_mercs.sp -o ../plugins/saxtonhale_mercs.smx